import { Section, SectionHead } from "@/components/ui/Section";
import { WhatsAppCta } from "@/components/ui/Cta";
import { Reveal } from "@/components/ui/Reveal";

/**
 * Three steps — CLAUDE.md §8.
 *
 * This is a genuine sequence, so numbering it is legitimate here. Per the
 * brief, nowhere else on the site gets numbered steps.
 */
const steps = [
  {
    title: "Send three photos",
    body: "Wide shot of the car, one of the damage, one close up. WhatsApp is quickest — no forms, no waiting on hold.",
  },
  {
    title: "We price it",
    body: "A real figure from a real estimator, not a range generated by a calculator. If we need to see it in person, we'll say so upfront.",
  },
  {
    title: "We handle the rest",
    body: "Booking, the insurer if there is one, courtesy transport, and the repair itself. You get the car back finished.",
  },
];

export function HowItWorks() {
  return (
    <Section tone="ink" labelledBy="how-heading">
      <SectionHead
        tone="ink"
        id="how-heading"
        eyebrow="How it works"
        title="Three steps, and most of them are ours."
        intro="You are probably standing next to a damaged car right now. This takes about two minutes of your time."
      />

      <ol className="mt-10 grid gap-px overflow-hidden rounded-[4px] border border-[var(--line)] bg-[var(--line)] sm:grid-cols-3">
        {steps.map((step, i) => (
          <Reveal key={step.title} as="li" delayMs={i * 90} className="group bg-[var(--steel)] p-6 transition-colors duration-300 hover:bg-[#212b3b]">
            {/* Numeral ghosts near-invisible until the card is hovered, then
                warms to red — the "colour-driven accent" asked for. */}
            <span
              aria-hidden
              className="font-display block text-[40px] leading-none text-[var(--line)] transition-colors duration-300 group-hover:text-[var(--red)]"
            >
              0{i + 1}
            </span>
            <h3 className="font-display mt-3 text-[20px] text-[var(--paper)]">
              <span className="sr-only">Step {i + 1}: </span>
              {step.title}
            </h3>
            <p className="mt-2.5 text-[15.5px] leading-[1.5] text-[var(--primer)]">{step.body}</p>
          </Reveal>
        ))}
      </ol>

      <div className="mt-8">
        <WhatsAppCta label="Start with photos" />
      </div>
    </Section>
  );
}
